void main(){
	pushi(ebp);
	move(esp, ebp);
	addi(-80, esp);
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(0, eax);
	move(0, ecx);
	addi(eax, ecx);
	addi(ebx, ecx);
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(0, eax);
	move(0, edx);
	addi(eax, edx);
	addi(ebx, edx);
	muli(ecx, edx);
	pushi(1);
	storei(edx, ind(esp));
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(0, eax);
	move(0, ecx);
	addi(eax, ecx);
	addi(ebx, ecx);
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(0, eax);
	move(0, edx);
	addi(eax, edx);
	addi(ebx, edx);
	muli(ecx, edx);
	loadi(ind(esp), eax);
	popi(1);
	addi(eax, edx);
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(-4, eax);
	muli(-16,ebx);
	addi(ebx,eax);
	addi(ebp, eax);
	loadi(ind(eax), eax);
	move(3, ebx);
	muli(-4,ebx);
	addi(ebx,eax);
	addi(ebp, eax);
	loadi(ind(eax), eax);
	move(0, ebx);
	move(0, ecx);
	addi(ebx, ecx);
	move(-4, ebx);
	muli(-16,ecx);
	addi(ecx,ebx);
	addi(ebp, ebx);
	loadi(ind(ebx), ebx);
	move(3, ecx);
	muli(-4,ecx);
	addi(ecx,ebx);
	addi(ebp, ebx);
	storei(edx,ind(ebx));
	print_string("value of a[0] is ");
	move(0, eax);
	move(-4, ebx);
	muli(-16,eax);
	addi(eax,ebx);
	addi(ebp, ebx);
	loadi(ind(ebx), ebx);
	move(3, eax);
	muli(-4,eax);
	addi(eax,ebx);
	addi(ebp, ebx);
	loadi(ind(ebx), ebx);
	print_int(ebx);
	print_string("\n");
	move(0, eax);
	j(Lmain_);
Lmain_:
	move(ebp, esp);
	loadi(ind(ebp), ebp);
	popi(1);
	return;
}

