void main(){
	pushi(ebp);
	move(esp, ebp);
	addi(-80, esp);
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(0, eax);
	move(0, ecx);
	addi(eax, ecx);
	addi(ebx, ecx);
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(0, eax);
	move(0, edx);
	addi(eax, edx);
	addi(ebx, edx);
	muli(ecx, edx);
	pushi(1);
	storei(edx, ind(esp));
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(1, eax);
	move(1, ecx);
	addi(eax, ecx);
	addi(ebx, ecx);
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(0, eax);
	move(1, edx);
	addi(eax, edx);
	addi(ebx, edx);
	muli(ecx, edx);
	loadi(ind(esp), eax);
	popi(1);
	addi(eax, edx);
	pushi(1);
	storei(edx, ind(esp));
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(1, eax);
	move(1, ecx);
	addi(eax, ecx);
	addi(ebx, ecx);
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(0, eax);
	move(1, edx);
	addi(eax, edx);
	addi(ebx, edx);
	muli(ecx, edx);
	loadi(ind(esp), eax);
	popi(1);
	addi(edx, eax);
	pushi(1);
	storei(eax, ind(esp));
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(0, eax);
	move(0, ecx);
	addi(eax, ecx);
	addi(ebx, ecx);
	move(0, eax);
	move(0, ebx);
	addi(eax, ebx);
	move(0, eax);
	move(0, edx);
	addi(eax, edx);
	addi(ebx, edx);
	muli(ecx, edx);
	loadi(ind(esp), eax);
	popi(1);
	addi(edx, eax);
	intTofloat(eax);
	move(1, ebx);
	move(1, ecx);
	addi(ebx, ecx);
	move(1, ebx);
	addi(ebx, ecx);
	move(1, ebx);
	addi(ebx, ecx);
	move(0, ebx);
	move(-4, edx);
	muli(-20,ebx);
	addi(ebx,edx);
	muli(-4,ecx);
	addi(ecx,edx);
	addi(ebp, edx);
	storef(eax,ind(edx));
	print_string("value of b[0][1] is ");
	move(0, eax);
	move(-4, ebx);
	muli(-20,eax);
	addi(eax,ebx);
	move(4, eax);
	muli(-4,eax);
	addi(eax,ebx);
	addf(ebp, ebx);
	loadf(ind(ebx), ebx);
	print_float(ebx);
	move(0, eax);
	j(Lmain_);
Lmain_:
	move(ebp, esp);
	loadi(ind(ebp), ebp);
	popi(1);
	return;
}

